server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders:
      - type: console

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://db.eexxrssfgrybcquoocne.supabase.co:5432/postgres?sslmode=require
  user: postgres
  password: qarsag-fodPav-3hegcu
  properties:
    charSet: UTF-8
    ssl: "true"
    sslfactory: org.postgresql.ssl.NonValidatingFactory
  maxWaitForConnection: 5s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 1
  maxSize: 4
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

supabase:
  jwtSecret: 81EF0C22-FB4C-4E42-BA53-FB0804129B63

logging:
  level: DEBUG
  loggers:
    com.ajayksingh.evenly: DEBUG
    org.jdbi: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: Asia/Kolkata
      logFormat: "%-5p [%d{ISO8601,Asia/Kolkata}] %c{1}: %m%n%rEx"
